In [32]:

import random
import numpy
 
matrix1 = []
matrix2 = []
answer = [[0]*3]*3


for i in range(3):
    a =[]
    for j in range(3):
         x=random.randint(0,9)
         a.append(int(x))
    matrix1.append(a)

print("matrix1 =")
for t in matrix1:
	print(t)



for i in range(3):
    b =[]
    for j in range(3):
         y=random.randint(0,9)
         b.append(int(y))
    matrix2.append(b)

print("\nmatrix2 =")
for s in matrix2:
	print(s)


answer = numpy.dot(matrix1,matrix2)

print("\n\nanswer =")
for r in answer:
	print(r)

matrix1 =
[5, 4, 3]
[9, 8, 9]
[0, 8, 1]

matrix2 =
[9, 7, 3]
[5, 9, 2]
[7, 4, 9]


answer =
[86 83 50]
[184 171 124]
[47 76 25]
